name: Django CI/CD Pipeline

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Create Firebase Credentials File
      run: |
        echo "${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}" | base64 -d > firebase-credentials.json

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DEBUG: 'False'
        ALLOWED_HOSTS: 'localhost 127.0.0.1'
        MYSQL_ENGINE: 'django.db.backends.sqlite3'
        MYSQL_DB: 'db.sqlite3'
        MYSQL_USER: 'dummy_user'
        MYSQL_PASSWORD: 'dummy_password'
        MYSQL_HOST: 'localhost'
        MYSQL_PORT: '3306'
        REDIS_URL: 'redis://localhost:6379/0'
        CSRF_TRUSTED_URLS: 'http://localhost http://127.0.0.1'
        EMAIL_HOST: 'smtp.gmail.com'
        EMAIL_PORT: '587'
        EMAIL_USE_TLS: 'True'
        EMAIL_HOST_USER: 'dummy@gmail.com'
        EMAIL_HOST_PASSWORD: 'dummy_password'
        CLOUD_NAME: 'dummy_cloud'
        API_KEY: '123456789'
        API_SECRET: 'dummy_secret'
        GOOGLE_CLIENT_ID: 'dummy_client_id'
        MOMO_PARTNER_CODE: 'dummny_code'
        MOMO_ACCESS_KEY: 'dummny_access_key'
        MOMO_SECRET_KEY: 'dummny_secret_key'
        MOMO_ENDPOINT: 'dummny_endpoint'
        MOMO_IPN_URL: 'ipn_dummy'
        STRIPE_PUBLISHABLE_KEY: 'publishable_dummy'
        STRIPE_SECRET_KEY: 'secret_key_dummy'
        STRIPE_WEBHOOK_SECRET: 'webhook_dummy'
        VNPAY_TMN_CODE: 'dummy_tmn'
        VNPAY_HASH_SECRET_KEY: 'hash_dummy'
        VNPAY_PAYMENT_URL: 'pay_url_dummy'
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Deploy to PythonAnywhere via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.PA_HOST }}
        username: ${{ secrets.PA_USERNAME }}
        key: ${{ secrets.PA_SSH_PRIVATE_KEY }}
        script: |
          set -e
          
          echo "ðŸš€ Starting Deployment..."
          
          cd ${{ secrets.PA_PROJECT_DIR }}
          
          git pull origin master
          
          source ${{ secrets.PA_VIRTUALENV_DIR }}/bin/activate
          
          pip install -r requirements.txt
          
          python manage.py migrate
          python manage.py collectstatic --noinput
          
          touch /var/www/www_clinicmanagement_com_wsgi.py
          
          echo "âœ… Deployment Successful!"
